[package]
name = "rust-gRPC-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.1"
tonic-reflection = "0.12.1"
prost = "0.13.1"
tokio = { version = "1.39.3", features = ["full"] }

[build-dependencies]
tonic-build = "0.9"